### ISSUE TITLE
Add ability to highlight specific fields by changing the background color

### ISSUE THREAD

**Issue by szsascha** [mganjoo/gchessboard#50]
Thanks for your great work!

Is there a possibility to change just the background color of a specific field? I couldn't find anything about it in your documentation.

An example usage are chess puzzles. A player wins a puzzle by moving one piece to one specific field. The player has to guess by himself which piece and position are the right ones.

If the player picked the correct field: the field shall be green. If the player picked the wrong field: the field shall be red.

**Comment by mganjoo** [comment]
Yep, this is achievable using "slots" - basically in gchessboard, any DOM element can be placed on a specific square by assigning the "slot" attribute.

In this case, your "background color of a specific square" can be achieved by thinking of it as a div overlay, with 100% width and height within a square, and styling that div with CSS.

Here's a quick CodePen with an example: https://codepen.io/mganjoo/pen/gOyGeOP

Is that what you were looking for?

**Comment by szsascha** [comment]
Oh wow, thank you very much!
That's exactly what I'm looking for.

The documentation about the slots sounded to me like a layer above the pieces. So I though if I'm using this, the whole field is red and the piece will not be visible anymore because it's under the red layer.

But now it's a layer between the piece and the real background. So this is exactly what I'm looking for. Thanks a lot!
