### ISSUE TITLE
User is unable to scroll the page if touch and drag gesture is initiated on top of the chessboard

### ISSUE THREAD

**Issue by hyperscientist** [mganjoo/gchessboard#51]
This is a problem on mobile devices. If chessboard covers full width of the screen then it also covers approximately half of the screen vertically, so oftentimes when user will want to scroll the page he will initiate the touch-and-drag gesture on top of the chessboard and it won't work how he expects (since nothing will happen).

The way it could work is to only prevent default browser behavior if user initially touches an interactive element, like a chess piece, and if the user starts his gesture on top of empty square then default browser behavior should not be prevented.

Btw, thanks for all the good work!

**Comment by mganjoo** [comment]
Yeah I had noticed that long ago and never got around to thinking through a solution. I like your idea of limiting scrollback; I will see if I can get around to it soon - not for the next few weeks realistically tbh (or feel free to open a PR if you like!)

**Comment by mganjoo** [comment]
The current behavior is actually done at a CSS level by using `user-action` and `touch-action` [here](https://github.com/mganjoo/gchessboard/blob/7c0f8248ea01633b858c855725727319199eef70/src/style.css#L81-L83). Moving this to within the JS code makes more sense and will allow more granular control.
